services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env
    networks:
      - app-network
    restart: unless-stopped
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
        NEXT_PUBLIC_URL: http://localhost:3000
    ports:
      - "3000:3000"
    env_file:
      - ./app/frontend/.env.local
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
