services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    networks:
      - app-network
    restart: unless-stopped
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
